name: Build-EXE
on: [push, workflow_dispatch]
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          # --- این خط را تغییر دهید ---
          python-version: '3.9'  # از 3.11 به 3.9 تغییر یافت

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt # مطمئن شوید tk-jalali-calendar با خط تیره است
          pip install pyinstaller

      - name: Package with PyInstaller
        run: |
          pyinstaller --onefile --noconsole ^
          --collect-data ttkbootstrap ^
          --hidden-import ttkbootstrap ^
          --hidden-import tk_jalali_calendar ^
          app3.py
          
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: app3
          path: dist/app3.exe
